-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users Table
create table public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null, -- Hashed password
  name text not null,
  company text,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Proposals Table
create table public.proposals (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  title text not null,
  client_name text not null,
  client_company text,
  client_email text,
  calculator_type text not null check (calculator_type in ('vmg', 'marine', 'marketing', 'custom')),
  calculator_data jsonb not null,
  content jsonb, -- AI generated content structure
  theme jsonb, -- Custom theme settings
  status text default 'draft' check (status in ('draft', 'sent', 'viewed', 'accepted', 'rejected')),
  view_count integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Proposal Links (for sharing)
create table public.proposal_links (
  id bigint generated by default as identity primary key,
  proposal_id bigint references public.proposals(id) on delete cascade,
  token text unique not null,
  password_hash text, -- Optional password protection
  expires_at timestamptz,
  max_views int,
  view_count int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

-- Proposal Views (Analytics)
create table public.proposal_views (
  id bigint generated by default as identity primary key,
  proposal_id bigint references public.proposals(id) on delete cascade,
  link_id bigint references public.proposal_links(id) on delete set null,
  session_id text not null,
  ip_address text,
  user_agent text,
  device_type text,
  browser text,
  os text,
  location text,
  duration_seconds int default 0,
  viewed_at timestamptz default now()
);

-- Proposal Interactions (Heatmaps/Events)
create table public.proposal_interactions (
  id bigint generated by default as identity primary key,
  view_id bigint references public.proposal_views(id) on delete cascade,
  proposal_id bigint references public.proposals(id) on delete cascade,
  interaction_type text not null, -- 'click', 'scroll', 'hover'
  element_id text,
  element_type text,
  x_position int,
  y_position int,
  scroll_depth int,
  timestamp timestamptz default now()
);

-- Proposal Comments
create table public.proposal_comments (
  id bigint generated by default as identity primary key,
  proposal_id bigint references public.proposals(id) on delete cascade,
  user_id bigint references public.users(id) on delete set null, -- Null if client comment
  author_name text not null,
  content text not null,
  is_internal boolean default false,
  created_at timestamptz default now()
);

-- Proposal Templates
create table public.proposal_templates (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  name text not null,
  description text,
  content_structure jsonb not null,
  theme jsonb,
  is_public boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Notifications
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  type text not null, -- 'view', 'accept', 'comment'
  title text not null,
  message text not null,
  data jsonb,
  is_read boolean default false,
  created_at timestamptz default now()
);

-- Indexes for performance
create index idx_proposals_user_id on public.proposals(user_id);
create index idx_proposal_links_token on public.proposal_links(token);
create index idx_proposal_views_proposal_id on public.proposal_views(proposal_id);
create index idx_proposal_interactions_view_id on public.proposal_interactions(view_id);
