-- Password Reset Tokens Table
-- This table stores temporary tokens for password reset functionality

create table if not exists public.password_reset_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  token text unique not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz default now()
);

-- Index for faster token lookups
create index if not exists idx_password_reset_tokens_token on public.password_reset_tokens(token);
create index if not exists idx_password_reset_tokens_user_id on public.password_reset_tokens(user_id);

-- Add RLS policies
alter table public.password_reset_tokens enable row level security;

-- Only allow service role to manage password reset tokens (no direct user access)
create policy "Service role can manage password reset tokens"
  on public.password_reset_tokens
  for all
  using (auth.role() = 'service_role');
