-- =============================================
-- MIGRATION: Add Invoices and Contracts Tables
-- Run this in Supabase SQL Editor (Dashboard > SQL)
-- =============================================

-- =============================================
-- TEMPLATES TABLE (for proposal templates)
-- =============================================
CREATE TABLE IF NOT EXISTS public.templates (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  name text not null,
  description text,
  content jsonb,
  category text,
  is_public boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- =============================================
-- CALCULATOR DEFINITIONS TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.calculator_definitions (
  id uuid default uuid_generate_v4() primary key,
  user_id bigint references public.users(id) on delete cascade,
  name text not null,
  description text,
  schema jsonb not null,
  is_public boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- =============================================
-- INVOICES TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.invoices (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  proposal_id bigint references public.proposals(id) on delete set null,
  invoice_number text unique not null,
  client_name text not null,
  client_company text,
  client_email text,
  client_address text,
  title text not null,
  line_items jsonb not null default '[]',
  subtotal numeric(12,2) default 0,
  tax_rate numeric(5,2) default 0,
  tax_amount numeric(12,2) default 0,
  discount_amount numeric(12,2) default 0,
  total numeric(12,2) default 0,
  amount_paid numeric(12,2) default 0,
  balance_due numeric(12,2) default 0,
  currency text default 'USD',
  due_date date,
  paid_at timestamptz,
  payment_terms text default 'net_30',
  milestone_number int default 1,
  milestone_total int default 1,
  notes text,
  status text default 'draft' check (status in ('draft', 'sent', 'viewed', 'paid', 'overdue', 'cancelled')),
  sent_at timestamptz,
  payment_link text,
  payment_platform text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- =============================================
-- INVOICE PAYMENTS TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.invoice_payments (
  id bigint generated by default as identity primary key,
  invoice_id bigint references public.invoices(id) on delete cascade,
  amount numeric(12,2) not null,
  payment_method text,
  transaction_id text,
  status text default 'completed',
  payment_date timestamptz default now(),
  metadata jsonb,
  created_at timestamptz default now()
);

-- =============================================
-- CONTRACT TEMPLATES TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.contract_templates (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  name text not null,
  description text,
  content text not null,
  placeholders jsonb default '[]',
  is_default boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- =============================================
-- CONTRACTS TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.contracts (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  proposal_id bigint references public.proposals(id) on delete set null,
  template_id bigint references public.contract_templates(id) on delete set null,
  access_token text unique not null,
  client_name text not null,
  client_company text,
  client_email text,
  client_address text,
  title text not null,
  content text not null,
  deliverables jsonb default '[]',
  total_value numeric(12,2),
  contract_term text,
  status text default 'draft' check (status in ('draft', 'sent', 'viewed', 'signed', 'countersigned', 'completed', 'cancelled')),
  sent_at timestamptz,
  viewed_at timestamptz,
  signed_at timestamptz,
  countersigned_at timestamptz,
  expires_at timestamptz,
  owner_signature_data text,
  owner_signed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- =============================================
-- CONTRACT SIGNATURES TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.contract_signatures (
  id bigint generated by default as identity primary key,
  contract_id bigint references public.contracts(id) on delete cascade,
  signer_name text not null,
  signer_email text,
  signature_data text not null,
  ip_address text,
  user_agent text,
  signed_at timestamptz default now()
);

-- =============================================
-- CLIENTS TABLE (for CRM)
-- =============================================
CREATE TABLE IF NOT EXISTS public.clients (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  name text not null,
  company text,
  email text,
  phone text,
  address text,
  notes text,
  tags text[],
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- =============================================
-- INDEXES FOR PERFORMANCE
-- =============================================
CREATE INDEX IF NOT EXISTS idx_invoices_user_id ON public.invoices(user_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON public.invoices(status);
CREATE INDEX IF NOT EXISTS idx_invoices_proposal_id ON public.invoices(proposal_id);
CREATE INDEX IF NOT EXISTS idx_contracts_user_id ON public.contracts(user_id);
CREATE INDEX IF NOT EXISTS idx_contracts_status ON public.contracts(status);
CREATE INDEX IF NOT EXISTS idx_contracts_access_token ON public.contracts(access_token);
CREATE INDEX IF NOT EXISTS idx_contract_signatures_contract_id ON public.contract_signatures(contract_id);
CREATE INDEX IF NOT EXISTS idx_templates_user_id ON public.templates(user_id);
CREATE INDEX IF NOT EXISTS idx_calculator_definitions_user_id ON public.calculator_definitions(user_id);
CREATE INDEX IF NOT EXISTS idx_clients_user_id ON public.clients(user_id);

-- =============================================
-- ENABLE ROW LEVEL SECURITY
-- =============================================
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calculator_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

-- =============================================
-- RLS POLICIES - Allow service role full access
-- (Your backend uses service_role key which bypasses RLS)
-- =============================================

-- Success message
DO $$
BEGIN
  RAISE NOTICE '✅ Migration completed successfully! Tables created: invoices, invoice_payments, contracts, contract_templates, contract_signatures, templates, calculator_definitions, clients';
END $$;
